spring:
  application:
    name: minipay
  datasource:
    url: jdbc:mysql://localhost:3308/minipay
    username: minipay
    password: minipay
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: always
